### PR TITLE
Updated to use latest revisions

### PR DESCRIPTION
**Pull request by gcphost**
Hey there.

Not sure if you're still using this project but it seems to fix exactly what I was wanting to start, so I've updated it to work with the latest releases.

I did tests all the routes, seems good.

### CODE REVIEW

**Comment by mrjgreen** [comment]
Hey thanks for this! I appreciate you taking the time to patch that up! I would say though, that this project is a bit outdated and maybe not the best example for you to use...

I have recently been working from another skeleton application that I've just pushed up to github here:

https://github.com/mrjgreen/skeleton-app

You should find that this is much easier to work with, allowing for:

 * Better dependency injection (on controllers too) 
 * Improved error handling
 * Service providers
 * Simple configuration (could combine with dotenv for environment based config)
 * Fully testable controllers and routes
 * Twig templating built in
 * Command line tool built in `./task` in base directory
 * Easy to run via php web server `./task serve` in base directory

Its a work in progress but definitely useable. I'll continue to push to this repo and I aim to push another branch with a full web app example, including login, registration, authentication and a simple admin area.

Would be happy to hear your thoughts on it!

**Comment by gcphost** [comment]
Awesome! Just saw it in my notifications before reading this. It does seem to be more inline with my goals. 

I'm going for the same results so maybe I'll wait and see how I can contribute to what you've created.

**Comment by gcphost** [comment]
I started to work a little bit on it but decided to stop, dont want to go back and re-do it all after you push some more updates.

I changed Config to use your old classes, so it's multi file, added Spot ORM, just to the DIC but nothing extra yet.

Check it out. I can post a merge for the Config if you want, would love to hear what ORM you plan to use.

https://github.com/Askedio/skeleton-app

**Comment by mrjgreen** [comment]
Looks good... I will be adding the config file back in in another branch of this.

For now I've added a new branch called "database" https://github.com/mrjgreen/skeleton-app/tree/database with an example of basic db usage.

There is no ORM as such in this example, I've gone for a lightweight DBAL and used a repository pattern. I find the repository pattern helps separate data access logic from entity objects even when the business logic starts to get complex. Just my opinion though :)

I'm going to continue this on another branch called "webapp" where I'm going to add in authentication, registration and login via forms etc... 

It will build on the UserRepository from this app.

**Pull request merged**
